"$schema": https://json-schema.org/draft/2020-12/schema
title: "Classification extension"
description: "STAC Classification Extension for STAC Items and STAC Collections."
allOf:
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/classification/v2.0.0/schema.json
