"$schema": https://json-schema.org/draft/2020-12/schema
allOf:
  - $ref: bblocks://ogc.geo.features.feature
  - $ref: bblocks://ogc.api.records.v1.schemas.recordGeoJSON
  - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://schemas.stacspec.org/v1.1.0/item-spec/json-schema/item.json
