"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection V1.0.0'
allOf:
  # - $ref: bblocks://ogc.geo.common.data_types.geojson
  - $ref: https://schemas.stacspec.org/v1.0.0/collection-spec/json-schema/collection.json
  - type: object
    properties:
      links:
        type: array
        items:
          $ref: bblocks://ogc.ogc-utils.json-link