"$schema": https://json-schema.org/draft/2020-12/schema
title: "STAC Extension for the ESA Open Science Catalog"
allOf:
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.item
    - $ref: bblocks://ogc.contrib.stac.collection-v1-0-0
    - $ref: bblocks://ogc.contrib.stac.item-v1-0-0
  - $ref: https://stac-extensions.github.io/osc/v1.0.0/schema.json
