"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection V1.0.0'
allOf:
  # - $ref: bblocks://ogc.geo.common.data_types.geojson
  - $ref: https://schemas.stacspec.org/v1.0.0/collection-spec/json-schema/collection.json
  - $ref: bblocks://ogc.contrib.stac.collection
  - type: object
    properties:
      stac-version:
        title: STAC version
        type: string
        const: 1.1.0
    required:
      - stac_version