"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection'
allOf:
  - $ref: bblocks://ogc.ogc-utils.prov#/$defs/Entity
  - $ref: https://github.com/radiantearth/stac-spec/raw/master/item-spec/json-schema/item.json
  - type: object
    properties:
      stac_extensions:
        type: array
        contains:
          const: https://stac-extensions.github.io/prov/v1.0.0/schema.json

