"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection'
allOf:
  - $ref: bblocks://ogc.ogc-utils.prov#/$defs/Entity
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.item
  - type: object
    properties:
      stac_extensions:
        type: array
        contains:
          const: https://stac-extensions.github.io/prov/v1.0.0/schema.json

