"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection'
allOf:
  - $ref: bblocks://ogc.geo.common.data_types.geojson
  - $ref: https://github.com/radiantearth/stac-spec/raw/master/item-spec/json-schema/item.json