"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection'
allOf:
  - $ref: bblocks://ogc.api.records.v1.schemas.recordGeoJSON
  - $ref: https://github.com/radiantearth/stac-spec/raw/master/item-spec/json-schema/item.json