"$schema": https://json-schema.org/draft/2020-12/schema
title: "Themes Extension"
description: "STAC Themes for STAC Items and STAC Collections."
allOf:
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/themes/v1.0.0/schema.json
