"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection'
allOf:
  - $ref: bblocks://ogc.geo.features.feature
  - $ref: bblocks://ogc.api.records.v1.schemas.recordGeoJSON
  - $ref: https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json