"$schema": https://json-schema.org/draft/2020-12/schema
description: 'STAC Collection'
allOf:
  # - $ref: bblocks://ogc.geo.common.data_types.geojson
  - $ref: https://github.com/radiantearth/stac-spec/raw/master/collection-spec/json-schema/collection.json
  - $ref: bblocks://ogc.api.features.v1.schemas.collection
  - $ref: bblocks://ogc.contrib.stac.collection-v1-0-0
  - type: object
    properties:
      links:
        type: array
        items:
          $ref: bblocks://ogc.ogc-utils.json-link