"$schema": https://json-schema.org/draft/2020-12/schema
title: "MLM extension"
description: "STAC MLM for STAC Items and STAC Collections."
allOf:
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/mlm/v1.4.0/schema.json
