"$schema": https://json-schema.org/draft/2020-12/schema
title: "CF Extension"
allOf:
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.item
  - $ref: https://stac-extensions.github.io/cf/v0.2.0/schema.json
