"$schema": https://json-schema.org/draft/2020-12/schema
title: "Themes Extension"
description: "STAC Themes for STAC Items and STAC Collections."
allOf:
  - anyOf:
    - $ref: bblocks://ogc.contrib.stac.collection
    - $ref: bblocks://ogc.contrib.stac.item
  # themes schema is version agnostic
  - $ref: https://stac-extensions.github.io/themes/v1.0.0/schema.json
  # bind the themes property to the lower level building block from Records (Common in future)
  - properties:
      themes:
        type: array
        items:
          $ref: bblocks://ogc.api.records.v1.schemas.theme
