"$schema": https://json-schema.org/draft/2020-12/schema
title: "Forecast Extension"
description: "STAC Forecast Extension for STAC Items and STAC Collections."
allOf:
  - anyOf:
    - $ref: ../../collection/schema.yaml
    - $ref: ../../item/schema.yaml
  - $ref: https://stac-extensions.github.io/eo/v1.1.0/schema.json
